name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'python:3.5.10-slim'
          - 'python:3.6.13-slim'
          - 'python:3.7.17-slim'
          - 'python:3.8.18-slim'
          - 'python:3.9.19-slim'
          - 'python:3.10.14-slim'
          - 'python:3.11.9-slim'
          - 'python:3.12.3-slim'
          - 'python:3.13.0-beta.1-slim'

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run pytest
        run: |
          pip install pytest
          pytest tests.py
