name: Python CI

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - 'python:3.5.10-slim'
          - 'python:3.6.13-slim'
          - 'python:3.7.17-slim'
          - 'python:3.8.18-slim'
          - 'python:3.9.19-slim'
          - 'python:3.10.14-slim'
          - 'python:3.11.9-slim'
          - 'python:3.12.3-slim'
          - 'python:3.13.3-slim'

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run tests and generate reports
        run: |
          pytest --cov=logfunc --cov-report=xml --html=report.html \
            --cov-report=term-missing --cov-fail-under=90 -vv \
            -s tests.py

      - name: Upload reports as artifacts
        if: matrix.image == 'python:3.11.9-slim'
        uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: |
            report.html
            coverage.xml
            assets/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Checkout gh-pages
        run: |
          git fetch
          if git branch -a | grep -q 'gh-pages'; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
            git add .
            git commit -m "Initial commit"
            git push -u origin gh-pages
          fi

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Reports

      - name: Add And Push
        run: |
          cp report.html index.html
          git status
          git add .
          git commit -m "Add report to pages"
          git push -f origin gh-pages
