name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'python:3.5.10-slim'
          - 'python:3.6.13-slim'
          - 'python:3.7.17-slim'
          - 'python:3.8.18-slim'
          - 'python:3.9.19-slim'
          - 'python:3.10.14-slim'
          - 'python:3.11.9-slim'
          - 'python:3.12.3-slim'

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          pip install pytest pytest-cov pytest-html

      - name: Run pytest with coverage
        run: |
          pytest --cov=logfunc --cov-report=xml --cov-report=html --html=report.html \
            --cov-fail-under=90 --cov-report=term-missing -svv -p no:warnings \
            tests.py
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: report.html

      - name: Upload XML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: coverage.xml

      - name: Upload coverage report to GitHub Pages
        run: |
          apt-get update && apt-get install -y git
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git fetch
          git checkout gh-pages || git checkout --orphan gh-pages
          mkdir reports
          mv report.html reports/${{ github.sha }}.html
          git add reports/${{ github.sha }}.html
          git commit -m "Add report for ${{ github.sha }}"
          git push origin gh-pages
