name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            '3.2.5',
            '3.3.5',
            '3.3.7',
            '3.4.10',
            '3.4.4',
            '3.5.10',
            '3.5.9',
            '3.6.14',
            '3.6.15',
            '3.7.16',
            '3.7.17',
            '3.8.17',
            '3.8.18',
            '3.9.18',
            '3.9.19',
            '3.13.0-alpha.6',
          ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run pytest
        run: |
          pip install pytest
          pytest
