name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          [
            'python:3.5.10-slim',
            '3.6.15',
            '3.7.17',
            '3.8.18',
            '3.9.19',
            '3.10.14',
            '3.11.9',
            '3.12.3',
            '3.13.0-beta.1',
          ]

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt

      - name: Run pytest
        run: |
          pip install pytest
          pytest
