name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - 'python:3.5.10-slim'
          - 'python:3.6.13-slim'
          - 'python:3.7.17-slim'
          - 'python:3.8.18-slim'
          - 'python:3.9.19-slim'
          - 'python:3.10.14-slim'
          - 'python:3.11.9-slim'
          - 'python:3.12.3-slim'

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt pytest pytest-cov pytest-html

      - name: Run tests and generate reports
        run: |
          pytest --cov=logfunc --cov-report=xml --html=report.html \
            --cov-report=term-missing --cov-fail-under=90 -vv \
            -s tests.py

      - name: Upload reports as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: |
            report.html
            coverage.xml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Reports

      - name: Configure git
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'

      - name: Publish coverage report to GitHub Pages
        run: |
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard
          cp report.html .
          git add report.html
          git commit -m "Update coverage report"
          git push origin gh-pages --force
